AWSTemplateFormatVersion: '2010-09-09'
Description: ECS-Fargate
Parameters:
  EnvironmentName:
    Type: String
    Default: ecs
    Description: "ECS-Fargate"
Resources:    
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${EnvironmentName}-fargate
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the ECS hosts that run containers
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}:VpcId
Outputs:
  ClusterName:
    Description: ECS-Fargate
    Value: !Ref 'ECSCluster'
    
  